### PR TITLE
fix: examples

### LINKED ISSUE #1630: Fix some Java examples
- [x] `ZeroTokenOperationsExample` - doesn’t work
- [x] `SolidityPrecompileExample` - doesn’t work with `hedera-local-node`
- [x] `ConsensusPubSubChunkedExample` - doesn’t work on CI

### PR DESCRIPTION
**Pull request by thenswan**
**Description**:
Fix examples and enable them in CI:
- `ZeroTokenOperationsExample`
- `SolidityPrecompileExample`
- `ConsensusPubSubChunkedExample`

Closes #1630

### CODE REVIEW

File: examples/src/main/java/com/hedera/hashgraph/sdk/examples/ConsensusPubSubChunkedExample.java [hunk 1]
```diff
@@ -122,7 +113,7 @@ public static void main(String[] args) throws TimeoutException, PrecheckStatusEx
         // get the receipt to ensure there were no errors
         transaction.execute(client).getReceipt(client);
 
-        boolean largeMessageReceived = largeMessageLatch.await(60, TimeUnit.SECONDS);
+        boolean largeMessageReceived = largeMessageLatch.await(180, TimeUnit.SECONDS);
```
Comment (0xivanov) [inline examples/src/main/java/com/hedera/hashgraph/sdk/examples/ConsensusPubSubChunkedExample.java:116]: This example can be flaky on localhost, i suggest running it at least 10 times to make sure it works

File: examples/src/main/java/com/hedera/hashgraph/sdk/examples/ZeroTokenOperationsExample.java [hunk 2]
```diff
@@ -77,14 +93,14 @@ public static void main(String[] args) throws Exception {
...
         // step 5 wipe the token by passing a zero value
-
         contractHelper.executeSteps(/* from step */ 0, /* to step */ 5, client);
 
         // step 6 use SDK and transfer passing a zero value
         // Create Fungible Token
         System.out.println("Attempting to execute step 6");
 
         TokenCreateTransaction tokenCreateTransaction = new TokenCreateTransaction()
+            .setMaxTransactionFee(new Hbar(50))
```
Comment (0xivanov) [inline examples/src/main/java/com/hedera/hashgraph/sdk/examples/ZeroTokenOperationsExample.java:103]: Don't we already set the max txn fee in ClientHelper

File: examples/src/main/java/com/hedera/hashgraph/sdk/examples/ZeroTokenOperationsExample.java [hunk 3]
```diff
@@ -66,9 +66,25 @@ public static void main(String[] args) throws Exception {
...
+            .setKey(KeyList.of(alicePublicKey, contractHelper.contractId).setThreshold(1))
+            .freezeWith(client)
+            .sign(alicePrivateKey)
+            .execute(client)
+            .getReceipt(client);
+
         // Configure steps in ContractHelper
         contractHelper
-            .setPayableAmountForStep(0, Hbar.from(20))
+            .setPayableAmountForStep(0, Hbar.from(40)) // is 40 Hbar needed?
```
Comment (0xivanov) [inline examples/src/main/java/com/hedera/hashgraph/sdk/examples/ZeroTokenOperationsExample.java:87]: 40 seems a lot but if it's for all the steps it might be ok

File: examples/src/main/java/com/hedera/hashgraph/sdk/examples/ConsensusPubSubChunkedExample.java (hunk 1 above)
Comment (thenswan) [reply examples/src/main/java/com/hedera/hashgraph/sdk/examples/ConsensusPubSubChunkedExample.java:116]: I agree, I have following observations:
- when I start local-node it doesn't work
- when I re-run example 10x times, it worked each time

cc @agadzhalov @isavov wdyt?

**Review by isavov — DISMISSED** [review]

File: examples/src/main/java/com/hedera/hashgraph/sdk/examples/ConsensusPubSubChunkedExample.java (hunk 1 above)
Comment (0xivanov) [reply examples/src/main/java/com/hedera/hashgraph/sdk/examples/ConsensusPubSubChunkedExample.java:116]: I think it's best to skip this test, as it might not even be designed to work on localhost.

**Review by 0xivanov — COMMENTED** [review]
Are the contracts getting compiled runtime? In Go we have hardcoded the bytecode, wondering if in Java there is a reason to update the `.sol` files.

**Comment by thenswan** [comment]
> Are the contracts getting compiled runtime?

No, also hardcoded.


> wondering if in Java there is a reason to update the .sol files.

I think its to show updates in bytecode. And for people to understand whats going on in the contract itself :) 

@0xivanov

File: gradle/plugins/src/main/kotlin/com.hedera.gradle.examples.java.gradle.kts [hunk 4]
```diff
@@ -77,9 +77,6 @@ abstract class RunAllExample : DefaultTask() {
             .asSequence()
             .map { it.name.replace(".java", "") }
             .filter { it != "ValidateChecksumExample" } // disabled this example, because it needs user input (but it WORKS)
-            .filter { it != "ZeroTokenOperationsExample" } // doesn't work
-            .filter { it != "SolidityPrecompileExample" } // doesn't work with hedera-local-node
-            .filter { it != "ConsensusPubSubChunkedExample" } // doesn't work on CI
```
Comment (0xivanov) [inline gradle/plugins/src/main/kotlin/com.hedera.gradle.examples.java.gradle.kts:82]: should revert the pub sub i think

**Comment by thenswan** [comment]
**The problem**
`ConsensusPubSubChunkedExample` in Java SDK is not working sometimes when running it against the local-node.

**How to reproduce**
Pre-requisites:
1. Clone Java SDK repo --> https://github.com/hashgraph/hedera-sdk-java
2. Configure dotenv --> https://github.com/hashgraph/hedera-sdk-java/blob/1c6325659557874479f3387b2f0f2028bd1870a1/examples/README.md#configuration

Steps to reproduce:
1. If Docker is running, then reopen the Docker (I mean exit the docker and run it again).
2. Start the local-node.
3. Run this command from the root of a project: `./gradlew :examples:runConsensusPubSubChunked`
Expected result:
ConsensusPubSubChunkedExample should fail the first time and then it should work any other time.

File: gradle/plugins/src/main/kotlin/com.hedera.gradle.examples.java.gradle.kts (hunk 4 above)
Comment (0xivanov) [reply gradle/plugins/src/main/kotlin/com.hedera.gradle.examples.java.gradle.kts:82]: @thenswan Do you want to skip this example for now and merge this PR. After it's fixed in local-node and has consistent behaviour we can enable it.

**Review by 0xivanov — APPROVED** [review]
LGTM
