### PR TITLE
fix: Android `toList` runtime issue

### LINKED ISSUE #1833: driod API 33, ContractFunctionResult using Stream ?   tripping up.    java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Ljava/util/stream/Stream
### Description

yeah.. kinda at a Client  impasse now @Datadamus  as unable to use HH SDK to read the Wallet Users profile SC and Query and Execution seem to use Stream dependency and it seems to not get sucked into emulator runtime  yet compile build is fine.

"   ContractFunctionResult result_1 = new ContractCallQuery()
                .setGas(30000)
                .setContractId(existing)
                .setFunction("getfname")
              //   .setMaxQueryPayment(new Hbar(1))
                .execute(USER_ACCOUNT);"

digging deeper ..  droid studio, 1.8 compat, compiling for API33.. droid 13..  HH SDK and gRPC is checked - as per github for droid..ok

droid does support java 8 from version 7 Nougat and Stream was in 8.  .  noted API26 hedera SDK min.

ContractFunctionResult using Stream ?    Studio config looks ok.   later in thread - copy of gradles.

Process: com.mvp.olarawallet, PID: 10463
                                                                                                    java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Ljava/util/stream/Stream; or its super classes (declaration of 'java.util.stream.Stream' appears in /apex/com.android.art/javalib/core-oj.jar)
                                                                                                    	at com.hedera.hashgraph.sdk.ContractFunctionResult.<init>(ContractFunctionResult.java:152)
                                                                                                    	at com.hedera.hashgraph.sdk.ContractCallQuery.mapResponse(ContractCallQuery.java:246)
                                                                                                    	at com.hedera.hashgraph.sdk.ContractCallQuery.mapResponse(ContractCallQuery.java:48)
                                                                                                    	at com.hedera.hashgraph.sdk.Executable$GrpcRequest.mapResponse(Executable.java:929)
                                                                                                    	at com.hedera.hashgraph.sdk.Executable.execute(Executable.java:463)
                                                                                                    	at com.hedera.hashgraph.sdk.Query.execute(Query.java:51)
                                                                                                    	at com.hedera.hashgraph.sdk.Executable.execute(Executable.java:364)
                                                                                                    	at com.hedera.hashgraph.sdk.Query.execute(Query.java:51)
                                                                                                    	at com.mvp.olarawallet.HederaServices.getacontract(HederaServices.java:357)
                                                                                                    	at com.mvp.olarawallet.MainActivity$LogonThread.run(MainActivity.java:251)
2024-06-02 11:29:15.501 10463-10497 Process                 com.mvp.olarawallet                  I  Sending signal. PID: 10463 SIG: 9

  ContractFunctionResult result_1 = new ContractCallQuery()
                .setGas(5000000)
                .setContractId(ContractId.fromString(existingcontractid))
                .setFunction("getfname")
                 .setMaxQueryPayment(new Hbar(5))
                .execute(USER_ACCOUNT);

        if (result_1.errorMessage!= null) {
            System.out.println("Error calling Contract " + result_1.errorMessage);
            return runitdetails;
        }

        String queryout = result_1.getString(0);

### Steps to reproduce

droid build. no probs

### Additional context

_No response_

### Hedera network

testnet

### Version

sdk and gPRC as in the Hedera repo READme - for droid for java sdk

### Operating system

None

### PR DESCRIPTION
**Pull request by 0xivanov**
**Description**:
The Java SDK is currently built using Java 17 and utilizes features and APIs up to Java 17. Therefore, it should be used by applications built with Java 17 or higher. However, Java 17 is only supported by the latest Android API (API level 34). 

Officially, Hedera claims that the Java SDK should be compatible with Android API level 26 and above.

The root cause of the issue is that when an Android application encounters a Java API call (such as `getModule`, `toList`, etc.) that it does not support—either due to an unsupported API level or other reasons like not supporting Java module system—it crashes at runtime. This issue is not detectable during compile time.

This PR removes usages of not supported functions where possible and adds docs to notify users for the specific Android API version supported for a given function.

Fixes #1833 #1620

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java [hunk 1]
```diff
@@ -1384,6 +1384,9 @@ public synchronized Duration getNetworkUpdatePeriod() {
     /**
      * Set the period for updating the Address Book
      *
+     * <p>Note: This method requires API level 33 or higher. It will not work on devices running API versions below 31
```
Comment (0xivanov) [inline sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java:1387]: Do not merge

**Review by agadzhalov — APPROVED** [review]
LGTM
