### PR TITLE
fix:reset setFileId and setContractId #1596

### LINKED ISSUE #1596: The setter methods `setFileId` and `setContractId` of `SystemDeleteTransaction.java` are not working as expected.
## 🆕🐥 First Timers Only

This issue is reserved for people who have never contributed to [Hedera](https://hedera.com) or any open source project in general.
We know that creating a pull request (PR) is a major barrier for new contributors.
The goal of this issue and all other issues labeled by [**'Good First Issue'**](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Ahashgraph+archived%3Afalse+label%3A%22Good+First+Issue%22+) is to help you make your first contribution to Hedera.

## 👾 Description of the issue

- The setter methods `setFileId` and `setContractId` in `SystemDeleteTransaction.java` are not behaving as expected. When `setFileId` is called, it should reset `contractId`, and similarly, when `setContractId` is called, it should reset `fileId`. However, this behavior is inconsistent between the **Java SDK** and the **C++ SDK**. The C++ SDK properly resets the other ID when one is set, but the Java SDK does not.

### Additional context
For reference, see the implementations:
- `setFileId` in the [Java SDK](https://github.com/hashgraph/hedera-sdk-java/blob/ef8db2e85eacb8902edb9115399f18c4bf2e365a/sdk/src/main/java/com/hedera/hashgraph/sdk/SystemDeleteTransaction.java#L103) vs the [C++ SDK](https://github.com/hashgraph/hedera-sdk-cpp/blob/8ef1414dcc4b05ea38b5653b135167673aa5adb5/sdk/main/src/SystemDeleteTransaction.cc#L58).
- `setContractId` in the [Java SDK](https://github.com/hashgraph/hedera-sdk-java/blob/ef8db2e85eacb8902edb9115399f18c4bf2e365a/sdk/src/main/java/com/hedera/hashgraph/sdk/SystemDeleteTransaction.java#L128C36-L128C49) vs the [C++ SDK](https://github.com/hashgraph/hedera-sdk-cpp/blob/8ef1414dcc4b05ea38b5653b135167673aa5adb5/sdk/main/src/SystemDeleteTransaction.cc#L67).

####  **Steps to Reproduce** 
1. Enable the `resetFileId` and `resetContractId` tests in `SystemDeleteTransactionTest`.
2. Run the tests and observe whether `setFileId` resets `contractId` and `setContractId` resets `fileId`.

### Proposed Solution:
To align the behavior of the Java SDK with the C++ SDK, the `setFileId` and `setContractId` methods in the Java implementation should be updated to reset the other field when one is set:
- **`setFileId`** should reset the `contractId` when it is called.
- **`setContractId`** should reset the `fileId` when it is called.

This can be achieved by modifying the methods in `SystemDeleteTransaction.java` to mirror the C++ implementation. For example:
```java
public SystemDeleteTransaction setFileId(FileId fileId) {
    requireNotFrozen();
    this.fileId = fileId;
    this.contractId = null; // Reset contractId
    return this;
}

public SystemDeleteTransaction setContractId(ContractId contractId) {
    requireNotFrozen();
    this.contractId = contractId;
    this.fileId = null; // Reset fileId
    return this;
}
```

Additionally, ensure that the tests are updated to reflect this behavior:
1. Re-enable the `resetFileId` and `resetContractId` tests in `SystemDeleteTransactionTest`.
2. Verify that both fields are properly reset by running these tests.

## 📋 Step by step guide to do a contribution

If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow. More information and concrete samples for shell commands for each step can be found in our [CONTRIBUTING.md](https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md) file.
A more detailed general documentation of the GitHub PR workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] **Claim this issue:** Comment below that you are interested in working on the issue
- [ ] **Wait for assignment:** A community member with the given rights will add you as an assignee of the issue
- [ ] **Fork the repository:** You can do that in GitHub (by simply clicking the 'fork' button).
- [ ] **Check out the forked repository**
- [ ] **Create a feature branch** for the issue. We do not have a hard naming definition for branches but it is best practice to prefix the branch name with the issue id.
- [ ] **Solve the issue** in your branch.
- [ ] **Commit your changes:** Here, it is needed to add `sign-off` information to the commit to accept the "Developer Certificate of Origin" (https://developercertificate.org). More details can be found in our [CONTRIBUTING.md](https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md)
- [ ] **Start a Pull Request (PR)**: We have a pattern for naming pull requests that a GitHub Action checks. We use that pattern to support the creation of automatic release notes.
- [ ] **Check GitHub Actions:** Several GitHub Actions will be triggered automatically for each PR. If a GitHub Action fails and you do not understand the cause of that error do not hesitate to add a comment to the PR and ask the Hedera developer community for support.
- [ ] **Wait for reviews:** Members of the Hedera developer community will review your PR. If a reviewer finds any missing pieces or a problem, he or she will start a discussion with you and describe the next steps for solving the problem.
- [ ] **You did it 🎉:** We will merge the fix in the develop branch. Thanks for being part of the Hedera community as an open-source contributor ❤️

## 🎉 Contribute to Hacktoberfest

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a chance to receive cool goodies like a T-Shirt. 🎽

## 🤔 Additional Information

If you have any questions, just ask us directly in this issue by adding a comment. You can join our community chat at [Discord](https://hedera.com/discord). A general manual about open-source contributions can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

### PR DESCRIPTION
**Pull request by jmiquis**
**Description**:

The setter methods setFileId and setContractId in SystemDeleteTransaction.java are not behaving as expected. This pr uses proposed solution
- code is working
- disable annotation and related comments removed from tests
- tests passes

**Related issue(s)**:

Fixes #1596

image

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: sdk/src/main/java/com/hedera/hashgraph/sdk/SystemDeleteTransaction.java [hunk 1]
```diff
@@ -100,9 +100,9 @@ public final FileId getFileId() {
      * @return {@code this}
      */
     public SystemDeleteTransaction setFileId(FileId fileId) {
-        Objects.requireNonNull(fileId);
```
Comment (0xivanov) [inline sdk/src/main/java/com/hedera/hashgraph/sdk/SystemDeleteTransaction.java:103]: Why delete this line?

Comment (jmiquis) [reply sdk/src/main/java/com/hedera/hashgraph/sdk/SystemDeleteTransaction.java:103]: MB, solved

**Review by 0xivanov — APPROVED** [review]
LGTM, nice work!

**Comment by jmiquis** [comment]
Thnx! Could you add the hacktoberfest-accepted label to this pr please?
