### PR TITLE
fix: block field and related logic for MirrorNodeContractQuery

### LINKED ISSUE #2612: Unable to query historical blocks via MirrorNodeContractQuery
### Description

The `MirrorNodeContractQuery` is unable to query historical blocks. The reason is because it's using an incorrect `blockNumber` field instead of the correct `block` field. The mirror node is ignoring the unknown field and defaulting to latest block.

Note that care should be taken to not regress this by just changing it to `block`. Doing that will then always send block zero if not set by user since the field is a primitive field that is always sent. Instead, make it a `Long` that is null so that if not set it defaults to empty which is latest. Document this behavior in the javadocs.

https://github.com/hiero-ledger/hiero-sdk-java/blob/c213bf8f55009822dc9c6ceac1c31d2930eb956c/sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNodeContractQuery.java#L313

Please also check other SDK languages for the same problem.

### Steps to reproduce

Run MirrorNodeContractQuery with setBlockNumber(someLong) and get latest results instead of historical.

### Additional context

_No response_

### Hedera network

other

### Version

2.66.0

### Operating system

None

### PR DESCRIPTION
**Pull request by mustafauzunn**
**Description**:

The `MirrorNodeContractQuery` cannot query historical blocks. The reason is that it's using an incorrect `blockNumber` field instead of the correct `block` field. The mirror node is ignoring the unknown field and defaulting to the latest block.

**Related issue(s)**:

Fixes #2612 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNodeContractQuery.java [hunk 1]
```diff
@@ -201,20 +202,20 @@ public T setGasPrice(long gasPrice) {
         return self();
     }
 
-    public long getBlockNumber() {
-        return this.blockNumber;
+    public long getBlock() {
+        return this.block;
```
Comment (hendrikebbers) [inline sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNodeContractQuery.java:206]: We have an auto boxing problem here since the field is defined as `Long` (allows `null` and initialized as `null`) but the method returns primitive `long`.

File: sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNodeContractQuery.java [hunk 2]
```diff
@@ -240,7 +241,7 @@ protected long estimate(Client client) throws ExecutionException, InterruptedExc
      */
     protected String call(Client client) throws ExecutionException, InterruptedException {
         fillEvmAddresses();
-        var blockNum = this.blockNumber == 0 ? "latest" : String.valueOf(this.blockNumber);
+        var blockNum = this.block != null ? String.valueOf(this.block) : null;
```
Comment (hendrikebbers) [inline sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNodeContractQuery.java]: Let's avoid to use `var`. especially in those conversations  it is misleading about the type.

File: sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNodeContractQuery.java [hunk 3]
```diff
@@ -265,7 +266,7 @@ private CompletableFuture<Long> getEstimateGasFromMirrorNodeAsync(Client client)
                 .thenApply(MirrorNodeContractQuery::parseHexEstimateToLong);
     }
 
-    private CompletableFuture<String> executeMirrorNodeRequest(Client client, String blockNumber, boolean estimate) {
+    private CompletableFuture<String> executeMirrorNodeRequest(Client client, String block, boolean estimate) {
```
Comment (hendrikebbers) [inline sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNodeContractQuery.java]: Why do we use String for it if it is only used with numeric input?

File: sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNodeContractQuery.java (hunk 1 above)
Comment (mustafauzunn) [reply sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNodeContractQuery.java:206]: Logic refactored

File: sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNodeContractQuery.java (hunk 2 above)
Comment (mustafauzunn) [reply sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNodeContractQuery.java]: Logic refactored

File: sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNodeContractQuery.java (hunk 3 above)
Comment (mustafauzunn) [reply sdk/src/main/java/com/hedera/hashgraph/sdk/MirrorNodeContractQuery.java]: Logic refactored

**Review by 0xivanov — APPROVED** [review]
LGTM
