### PR TITLE
Fixing timeout for `TransactionResponse#getReceipt` not working well

### LINKED ISSUE #1497: Timeout for TransactionResponse.getReceipt  not working well
### Description

# Description
When I set the timeout for getReceipt as 1 sec, it works fine - it waits for exact 1 second and throws TimeoutException.
By the way, when I set the timeout as 2 to 10, it works weird - it waits for exact 10 seconds and throws TimeoutException.
`Duration.ofSeconds(2)` ~ `Duration.ofSeconds(10)`

It worked same when I use `Duration.ofMills(2000))` - it waits for 10 seconds, not 2 seconds.

Please let me know if there is another factor for timeout amount of getReceipt.

# Problem
- getReceipt's timeout setting does not work as expected. For example, 
    - If I set 1 second, it waits 1 second. -> OK
    - If I set 2 seconds, it waits 10 seconds, not 2 seconds -> NOK
    - If I set 3 seconds, it waits 10 seconds, not 3 seconds -> NOK
    - ...

# Expected result
- getReceipt should wait for the exact time as I set.

### Steps to reproduce

Please see the code below.

### Additional context

```java
// After executing transaction..

int HEDERA_TESTNET_TIMEOUT_SEC = 1 // Timeout amount for getReceipt (sec)
try {
     TransactionReceipt receipt = transactionResponse.getReceipt(client, Duration.ofSeconds(HEDERA_TESTNET_TIMEOUT_SEC)));
 } catch (java.util.concurrent.TimeoutException e) {
     Log.e("cannot get the receipt for timeout" + e);
 }

```

### Hedera network

testnet

### Version

v2.22.0

### Operating system

macOS

### PR DESCRIPTION
**Pull request by thenswan**
**Description**:
Fix for issue timeout for `TransactionResponse.getReceipt` not working well. 

**Related issue(s)**:
Fixes #1497

**Checklist**
- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by rokn — APPROVED** [review]

File: sdk/src/test/java/com/hedera/hashgraph/sdk/ExecutableTest.java [hunk 1]
```diff
@@ -335,7 +342,8 @@ TransactionResponse mapResponse(com.hedera.hashgraph.sdk.proto.TransactionRespon
                 .build();
 
         tx.blockingUnaryCall = (grpcRequest) -> txResp;
-        com.hedera.hashgraph.sdk.TransactionResponse resp = (com.hedera.hashgraph.sdk.TransactionResponse) tx.execute(client);
+        com.hedera.hashgraph.sdk.TransactionResponse resp = (com.hedera.hashgraph.sdk.TransactionResponse) tx.execute(
+            client);
```
Comment (rokn) [inline sdk/src/test/java/com/hedera/hashgraph/sdk/ExecutableTest.java:346]: This formatting looks really strange

**Review by rokn — APPROVED** [review]

File: sdk/src/test/java/com/hedera/hashgraph/sdk/ExecutableTest.java (hunk 1 above)
Comment (thenswan) [reply sdk/src/test/java/com/hedera/hashgraph/sdk/ExecutableTest.java:346]: @rokn agree, I mentioned it on our sync
